# Generated by Django 5.1.1 on 2024-09-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="price",
        ),
    ]
