# Generated by Django 5.1.1 on 2025-04-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_itemtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('receive', 'รับเข้า'), ('issue', 'จ่ายออก')], db_index=True, max_length=10),
        ),
    ]
