# Generated by Django 5.1.1 on 2025-04-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_itemtransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='items',
            name='alert_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
