# Generated by Django 5.1.1 on 2025-05-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_items_options_items_alert_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('receive', 'รับเข้า'), ('issue', 'จ่ายออก'), ('update', 'อัปเดต')], db_index=True, max_length=10),
        ),
    ]
