# Generated by Django 5.1.1 on 2024-09-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="nick_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
