-- system user
INSERT INTO auth_user (password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) VALUES ('password', NOW(), false, 'system', 'system', 'system', 'email@email.com', false, true, NOW()) ON CONFLICT DO NOTHING;

-- stock_category
INSERT INTO stock_category (deleted, deleted_by_cascade, created_date, name, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'น้ำพริก', 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_category (deleted, deleted_by_cascade, created_date, name, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจล', 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_category (deleted, deleted_by_cascade, created_date, name, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'กล่องโฟม', 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_category (deleted, deleted_by_cascade, created_date, name, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ฟอยล์', 1, 1) ON CONFLICT DO NOTHING;
-- stock_unit
INSERT INTO stock_units (deleted, deleted_by_cascade, created_date, name, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'กระปุก', 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_units (deleted, deleted_by_cascade, created_date, name, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ชิ้น', 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_units (deleted, deleted_by_cascade, created_date, name, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'กล่อง', 1, 1) ON CONFLICT DO NOTHING;

-- stock_items
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'มันกุ้ง', 'FG-MG01', 'MMAPMK000001', 0, 0.0, 1, 1, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'อ่องปูนา', 'FG-APN02', 'MMAPAN000001', 0, 0.0, 1, 1, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'มันปูเข้มข้น', 'FG-MPK03', 'MMAPPK000001', 0, 0.0, 1, 1, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'น้ำพริกมันปูม้า', 'FG-NPPM04', 'MMAPPM000001', 0, 0.0, 1, 1, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'กุ้งใหญ่', 'FG-GY05', 'MMAPKB000001', 0, 0.0, 1, 1, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ปูใหญ่', 'FG-PY06', 'MMAPPB000001', 0, 0.0, 1, 1, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เข้มใหญ่', 'FG-KY07', 'MMAPKB000001', 0, 0.0, 1, 1, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'น้ำพริกใหญ่', 'FG-NPY08', 'MMAPNB000001', 0, 0.0, 1, 1, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ซีฟู้ด', 'FG-SF09', 'MMAPSE000001', 0, 0.0, 1, 1, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'สาหร่าย', 'FG-SA10', 'MMAPSL000001', 0, 0.0, 1, 1, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจล 20g', 'G-020', 'MMGN20000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจล 50g', 'G-050', 'MMGN50000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจล 100g', 'G-100', 'MMGN10000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจล 200g', 'G-200', 'MMGN20000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจล 300g', 'G-300', 'MMGN30000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจล 400g', 'G-400', 'MMGN40000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจล 500g', 'G-500', 'MMGN50000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจลใส 100', 'GZ-100', 'MMGZ10000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจลใส 200', 'GZ-200', 'MMGZ20000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจลใส 400', 'GZ-400', 'MMGZ40000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจลกล่องเล็ก', 'GB-S', 'MMGBSS000001', 0, 0.0, 3, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจลกล่องกลาง', 'GB-M', 'MMGBMM000001', 0, 0.0, 3, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจลกล่องใหญ่', 'GB-L', 'MMGBLL000001', 0, 0.0, 3, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจลกล่องใหญ่1000', 'GB-L1000', 'MMGBXL000001', 0, 0.0, 3, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจลขาว 100', 'GW-100', 'MMGW10000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจลขาว 200', 'GW-200', 'MMGW20000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจลขาว 400', 'GW-400', 'MMGW40000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจลขาว 600', 'GW-600', 'MMGW60000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจลขาว 800', 'GW-800', 'MMGW80000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจลขาว 1000', 'GW-1000', 'MMGWX0000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจล100แช่น้ำ', 'GW-W100', 'MMGA10000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจล200แช่น้ำ', 'GW-W200', 'MMGA20000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจล400แช่น้ำ', 'GW-W400', 'MMGA40000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'เจล7×7แช่น้ำ', 'GW-W7070', 'MMGA70000001', 0, 0.0, 2, 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'กล่องโฟม 1kg', 'FM-01', 'MMFM10000001', 0, 0.0, 3, 3, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'กล่องโฟม 2kg', 'FM-02', 'MMFM20000001', 0, 0.0, 3, 3, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'กล่องโฟม 3kg', 'FM-03', 'MMFM30000001', 0, 0.0, 3, 3, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'กล่องโฟม 5kg', 'FM-05', 'MMFM50000001', 0, 0.0, 3, 3, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'กล่องโฟม 10kg', 'FM-10', 'MMFMX0000001', 0, 0.0, 3, 3, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'กล่องโฟม 20kg', 'FM-20', 'MMFMXX000001', 0, 0.0, 3, 3, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'กล่องโฟม 25kg', 'FM-25', 'MMFMXV000001', 0, 0.0, 3, 3, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ฟอย20×20', 'FOIL-2020', 'MMFL20200001', 0, 0.0, 2, 4, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ฟอย20×25', 'FOIL-2025', 'MMFL20250001', 0, 0.0, 2, 4, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ฟอย25×30', 'FOIL-2530', 'MMFL25300001', 0, 0.0, 2, 4, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ฟอย30×30', 'FOIL-3030', 'MMFL30300001', 0, 0.0, 2, 4, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ฟอย30×40', 'FOIL-3040', 'MMFL30400001', 0, 0.0, 2, 4, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ฟอย40×40', 'FOIL-4040', 'MMFL40400001', 0, 0.0, 2, 4, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ฟอย40×50', 'FOIL-4050', 'MMFL40500001', 0, 0.0, 2, 4, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ฟอย50×50', 'FOIL-5050', 'MMFL50500001', 0, 0.0, 2, 4, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ฟอย21×10×23', 'FOILB-211023', 'MMFB21102301', 0, 0.0, 2, 4, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ฟอย24×24×28', 'FOILB-242428', 'MMFB24242801', 0, 0.0, 2, 4, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ฟอย29×17×26', 'FOILB-291726', 'MMFB29172601', 0, 0.0, 2, 4, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ฟอย34×14×30', 'FOILB-341430', 'MMFB34143001', 0, 0.0, 2, 4, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO stock_items (deleted, deleted_by_cascade, created_date, name, barcode, sku, amount, price_per_unit, unit_id, category_id, created_by_id, updated_by_id) VALUES (null, false, NOW(), 'ฟอย17×17×22', 'FOILB-171722', 'MMFB17172201', 0, 0.0, 2, 4, 1, 1) ON CONFLICT DO NOTHING;